import keyMirror from 'keymirror';

export default keyMirror({
  FETCH_MEMBER: null,
  FETCH_USER: null,
  FETCH_MEMBER_EMAIL: null,
  UPDATE_MEMBER_EMAIL: null,
  UPDATE_MEMBER_PASSWORD: null,
  FETCH_NOTIFICATIONS_LIST: null,
  MARK_ALL_NOTIFICATIONS_AS_READ: null,
  MARK_NOTIFICATION_AS_READ: null,
  DELETE_NOTIFICATION: null,
  CLEAR_NOTIFICATIONS_LIST: null,
  FETCH_MEMBER_YEAR_STATS: null
});
