import keyMirror from 'keymirror';

export default keyMirror({
  FETCH_SHOW_CHARACTERS: null,
  FETCH_SHOW_EPISODES: null,
  FETCH_SIMILAR_SHOWS: null,
  FETCH_FAVORITE_SHOWS: null,
  FETCH_MANY_SHOWS: null,
  FETCH_SHOW: null,
  FETCH_EPISODE: null,
  FETCH_MANY_EPISODES: null,
  FETCH_LATEST_EPISODE: null,
  FETCH_EPISODE_BY_CODE: null,
  FETCH_EPISODES_LIST: null,
  FETCH_DISCOVER_SHOWS: null,
  ADD_SHOW: null,
  REMOVE_SHOW: null,
  RATE_SHOW: null,
  MARK_EPISODE_AS_WATCHED: null,
  MARK_MANY_EPISODE_AS_WATCHED: null,
  ADD_SHOW_FAVORITE: null,
  UNMARK_EPISODE_AS_WATCHED: null,
  UNMARK_MANY_EPISODE_AS_WATCHED: null,
  REMOVE_SHOW_FAVORITE: null
});
